In [1]:
import numpy as np 

In [3]:
arr = np.array([1,2,3,4,5])
print("Array:", arr)

Array: [1 2 3 4 5]


### Addition ---->

In [13]:
add_arr = arr + 2
add_arr

array([3, 4, 5, 6, 7])

### Subtraction ---->

In [9]:
sub_arr = arr - 2
sub_arr

array([-1,  0,  1,  2,  3])

### Multiplication ---->

In [16]:
mul_arr = arr * 2
mul_arr

array([ 2,  4,  6,  8, 10])

### Division ---->

In [26]:
div_arr = arr / 2
div_arr

array([0.5, 1. , 1.5, 2. , 2.5])

### Indexing & Slicing ---->

In [33]:
element1 = arr[1]
element2 = arr[2]

print("Element_1:", element1)
print("Element_2:", element2)

slice = arr[2:4]
print("Slicing Array:", slice)

Element_1: 2
Element_2: 3
Slicing Array: [3 4]


### Reshaping Array ---->

In [49]:
reshape_arr = arr.reshape(5,1)
print(reshape_arr)

[[1]
 [2]
 [3]
 [4]
 [5]]


### Transposing Matrices ---->

In [54]:
transpose_arr = reshape_arr.T
print("Transposed Array: ", transpose_arr)

Transposed Array:  [[1 2 3 4 5]]


### Statistical Functions ---->

In [57]:
mean = np.mean(arr)
mean

3.0

In [61]:
median = np.median(arr)
median

3.0

In [63]:
std_dev = np.std(arr)
std_dev


1.4142135623730951

In [65]:
var = np.var(arr)
var

2.0

### Data Types In Arrays ---->

In [90]:
int_arr = np.array(arr, dtype=int)
print("Integer: ",int_arr)

Integer:  [1 2 3 4 5]


In [82]:
float_arr = np.array(arr, dtype=float)
print("float:",float_arr)

float: [1. 2. 3. 4. 5.]


In [84]:
bool_arr= np.array(arr, dtype=bool)
print("Boolean: ",bool_arr)

Boolean:  [ True  True  True  True  True]


In [88]:
str_arr = np.array(arr, dtype=str)
print("String: ",str_arr)

String:  ['1' '2' '3' '4' '5']


### Concatenating Array ---->

In [95]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print("Concatenated Array:", concatenated_arr)

Concatenated Array: [1 2 3 4 5 6]


### Sorting Arrays ---->

In [98]:
unsorted_array = np.array([3, 1, 2, 5, 4])
sorted_array_asc = np.sort(unsorted_array)  
sorted_array_desc = np.sort(unsorted_array)[::-1]  

print("Sorted Array (Ascending):", sorted_array_asc)
print("Sorted Array (Descending):", sorted_array_desc)

Sorted Array (Ascending): [1 2 3 4 5]
Sorted Array (Descending): [5 4 3 2 1]


In [1]:
import pandas as pd

In [3]:
data_csv = pd.read_csv("student data.csv")
data_csv

roll no       Name  Chemistry  Physics  Math
0       101      Aliza         50       23    87
1       102     Fareed         45       24    88
2       103      Basit         46       25    89
3       104   Abdullah         47       26    90
4       105        Ali         48       27    67
5       106   Mubashir         49       28    68
6       107     Waleed         50       29    69
7       108    Mansoor         51       30    70
8       109       Zain         52       31    71
9       110     Mohsin         53       67    72
10      111   Shahmeer         54       68    73
11      112        Rao         55       69    74
12      113  Aurangzeb         56       70    75
13      114    Zeeshan         57       71    76
14      115      Hamna         58       72    77
15      116      Hamza         59       73    78
16      117     Khalid         60       74    79
17      118     Behroz         61       75    80
18      119     Justin         62       76    81
19      120     Danish         63       77    82
20      121     Kainat         64       78    83
21      122     Sameer         65       79    84
22      123       Raza         66       80    85
23      124      Kumar         67       81    86
24      125      Komal         68       82    87
25      126       Erum         69       83    88
26      127      Faiza         70       84    89
27      128      Saeed         71       85    90
28      129      Waqar         72       86    91
29      130       Wali         73       87    92
30      131      Wajid         74       88    93
31      132     Waseeb         75       89    94
32      133      Shiza         76       90    95
33      134    Shabina         77       91    96
34      135    Shazain         78       55    97
35      136      Lubna         79       61    98
36      137      Laiba         80       88    78
37      138  Khursheed         81       56    45
38      139        Ali         82       89    46
39      140       Aiza         83       45    89
40      141      Aiman         84       92    78
41      142    Yasmeen         85       36    56
42      143    Tasbeel         86       78    78
43      144     Laraib         87       56    54
44      145     Saleem         88       78    78
45      146     Bismil         89       89    46
46      147     Batool         90       56    79
47      148       Iqra         91       33    46
48      149    Zarnish         92       78    45
49      150       Zara         83       45    56

In [7]:
print(data_csv.shape)

(50, 5)


In [9]:
print(data_csv.dtypes)

roll no       int64
Name         object
Chemistry     int64
Physics       int64
Math          int64
dtype: object


In [11]:
print(data_csv.isnull().sum())

roll no      0
Name         0
Chemistry    0
Physics      0
Math         0
dtype: int64


In [15]:
summary_stats = data_csv.describe()
summary_stats_all = data_csv.describe(include='all')
print(summary_stats)
print(summary_stats_all)

         roll no  Chemistry    Physics       Math
count   50.00000  50.000000  50.000000  50.000000
mean   125.50000  68.420000  65.060000  77.360000
std     14.57738  14.116266  22.676437  14.789351
min    101.00000  45.000000  23.000000  45.000000
25%    113.25000  56.250000  47.500000  71.250000
50%    125.50000  68.500000  73.500000  79.000000
75%    137.75000  80.750000  82.750000  88.750000
max    150.00000  92.000000  92.000000  98.000000
          roll no Name  Chemistry    Physics       Math
count    50.00000   50  50.000000  50.000000  50.000000
unique        NaN   49        NaN        NaN        NaN
top           NaN  Ali        NaN        NaN        NaN
freq          NaN    2        NaN        NaN        NaN
mean    125.50000  NaN  68.420000  65.060000  77.360000
std      14.57738  NaN  14.116266  22.676437  14.789351
min     101.00000  NaN  45.000000  23.000000  45.000000
25%     113.25000  NaN  56.250000  47.500000  71.250000
50%     125.50000  NaN  68.500000  73.500000  

KeyError: "None of [Index(['column1', 'column2'], dtype='object')] are in the [columns]"